### ISSUE TITLE
Mostly NO DATA after plug smart extra battery (DELTA 2 in my case)

### ISSUE THREAD

**Issue by OsokinDenys** [berezhinskiy/ecoflow_exporter#59]
After plug smart extra battery  have mostly  NO DATA on dashboard.
![image](https://github.com/berezhinskiy/ecoflow_exporter/assets/150661124/56e58bb8-30e2-4b8b-910a-2e9e9e129576)
In docker log have some like:
`2024-06-27 09:38:02,067 INFO    Created new metric from payload key bms_bmsStatus.actSoc -> ecoflow_bms_bms_status_act_soc
2024-06-27 09:38:02,067 WARNING Skipping unsupported metric bms_bmsStatus.cellVol: [3277, 3285, 3285, 3282, 3285, 3278, 3281, 3286, 3286, 3282, 3286, 3286]
2024-06-27 09:38:02,068 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:02,069 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:12,070 INFO    Processing 9 event(s) from the message queue
2024-06-27 09:38:12,072 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:12,072 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:12,074 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:12,075 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:12,077 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:12,077 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:12,078 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:12,079 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:12,081 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:12,081 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:22,083 INFO    Processing 10 event(s) from the message queue
2024-06-27 09:38:22,084 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:22,085 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:22,086 WARNING Skipping unsupported metric bms_kitInfo.watts: [{'appState': 1, 'curPower': -24, 'appVer': 34275944, 'f32Soc': 59.8, 'soc': 60, 'avaFlag': 1, 'sn': 'R341Z1XXXXXXXXXXX', 'detail': 4, 'type': 80, 'loadVer': 34275328}, {'appState': 0, 'curPower': 0, 'appVer': 0, 'f32Soc': 0, 'soc': 0, 'avaFlag': 0, 'sn': '', 'detail': 0, 'type': 0, 'loadVer': 0}]
2024-06-27 09:38:22,088 WARNING Skipping unsupported metric bms_bmsStatus.cellTemp: []
2024-06-27 09:38:22,088 WARNING Skipping unsupported metric bms_bmsStatus.cellVol: [3285, 3285, 3279, 3277, 3279, 3282, 3283, 3282, 3282, 3283, 3283]
2024-06-27 09:38:22,089 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:22,090 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:22,090 WARNING Skipping unsupported metric pd.icoBytes: [32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
2024-06-27 09:38:22,092 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:22,092 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:22,094 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:22,095 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:32,096 INFO    Processing 9 event(s) from the message queue
2024-06-27 09:38:32,098 WARNING Skipping unsupported metric bms_slave.cellVol: []
2024-06-27 09:38:32,099 WARNING Skipping unsupported metric bms_slave.cellTemp: []
2024-06-27 09:38:32,101 WARNING Skipping unsupported metric bms_slave.cellVol: []` 

where 'sn': 'R341Z1XXXXXXXXXXX',  - is smart extra battery SN, it's can't add to mobile app

also in log
`Traceback (most recent call last):
  File "/ecoflow_exporter.py", line 365, in <module>
    main()
  File "/ecoflow_exporter.py", line 357, in main
    metrics.loop()
  File "/ecoflow_exporter.py", line 262, in loop
    self.process_payload(params)
  File "/ecoflow_exporter.py", line 292, in process_payload
    metric.set(ecoflow_payload_value)
  File "/ecoflow_exporter.py", line 217, in set
    self.metric.labels(device=self.device_name).set(value)
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/metrics.py", line 417, in set
    self._value.set(float(value))
                    ^^^^^^^^^^^^
ValueError:  could not convert string to float: 'R341Z1XXXXXXXXXXX'`

**Comment by pontostroy** [comment]
https://github.com/berezhinskiy/ecoflow_exporter/issues/48
