### ISSUE TITLE
MQTT messages can not get encoded/parsed

### ISSUE THREAD

**Issue by kalle8888** [berezhinskiy/ecoflow_exporter#77]
Hi,
just to warn you before, I have not clue about MQTT .... nor of PY

Anyway....after found in #34 that my first problem ("message queue is empty") is known and I can bypass it by starting the app in parallel, I get a second error that I could not find under "issues".

Something must go wrong when processing the messages. I would think that a charakter x88 in not understood. 

Would you please check the following log and help me.
Thank you
/Kalle

P.S. I also tried to change the ENV Variable in docker to UTF-8, en_US.UTF-8 and de_DE.UTF-8 but this did not help

Container LOG:
=================

2024-10-13 12:01:30,895 INFO    Successfully logged in: xxxxxxxxx
2024-10-13 12:01:30,895 INFO    Requesting IoT MQTT credentials https://api.ecoflow.com/iot-auth/app/certification
2024-10-13 12:01:30,943 INFO    Successfully extracted account: app-a95e69xxxxxxxxxxxxxxxxxxxxxxxxxxx
2024-10-13 12:01:30,984 INFO    Connecting to MQTT Broker mqtt-e.ecoflow.com:8883 using client id ANDROID_Fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2024-10-13 12:01:31,031 INFO    Subscribed to MQTT topic /app/device/property/HWxxxxxxxxxxxxxxxxxxxx
Exception in thread paho-mqtt-client-ANDROID_Fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4523, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/ecoflow_exporter.py", line 187, in on_message
    self.message_queue.put(message.payload.decode("utf-8"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte**
2024-10-13 12:01:41,013 INFO    Message queue is empty. Assuming that the device is offline

**Comment by kalle8888** [comment]
In the meanwhile I am very sure that the error comes from the DATA itself.

I changed the decode statement to ignore decoding errors by changing the code line to 
......message.payload.decode("utf-8",errors="ignore"))

and now  the data can not get parsed

the data is shown in the log (I can not copy paste it here, since it can't get displayed, so I have to use a screen shot of the log, opened in an editor)

Failed to parse MQTT payload: 

![grafik](https://github.com/user-attachments/assets/dfbc55f3-dce0-4f0a-8c05-d8dbc70fb6a2)

**Comment by kalle8888** [comment]
nioupola,
I looked at it, but honestly I do not see a solution in that posting for my problem (I am also not so experienced in programming, so I might do not understand what you like to tell me).

What do I need to do ?
Thanks
/Kalle

**Comment by maurobotta** [comment]
New micro inverter 2025 , don't work.   always error:    UnicodeDecodeError:  codec 'utf-8'

**Comment by oleua** [comment]
Hi! With my River 2 Plus I am never getting MQTT messages in the dashboard, though the figures are updated:

<img width="1885" height="673" alt="Image" src="https://github.com/user-attachments/assets/d0648cb4-8232-4b54-8cde-40c24eea8c94" />

So, specifically this parameter is not providing data `rate(ecoflow_mqtt_messages_receive_total{device="****"}[1m])`, and
`ecoflow_mqtt` is not discoverable at all:


<img width="828" height="345" alt="Image" src="https://github.com/user-attachments/assets/160d0057-a66c-4308-b860-ed4e99362d05" />

**Comment by erebion** [comment]
I don't get anything with a Stream Micro Inverter. Dashboard shows nothing.

The endpoint just returns:

```
# HELP ecoflow_online 1 if device is online
# TYPE ecoflow_online gauge
ecoflow_online{device="BKxxxxxxxxxxxxxx"} 0.0
# HELP ecoflow_mqtt_messages_receive_total total MQTT messages
# TYPE ecoflow_mqtt_messages_receive_total counter
```

**Comment by erebion** [comment]
> I don't get anything with a Stream Micro Inverter. Dashboard shows nothing.

Here's the log:

```
ecoflow_exporter  | 2026-04-09 12:03:49,344 INFO    Login to EcoFlow API https://api.ecoflow.com/auth/login
ecoflow_exporter  | 2026-04-09 12:03:49,497 INFO    Successfully logged in: EcoFlow User
ecoflow_exporter  | 2026-04-09 12:03:49,497 INFO    Requesting IoT MQTT credentials https://api.ecoflow.com/iot-auth/app/certification
ecoflow_exporter  | 2026-04-09 12:03:49,629 INFO    Successfully extracted account: app-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ecoflow_exporter  | 2026-04-09 12:03:49,682 INFO    Connecting to MQTT Broker mqtt-e.ecoflow.com:8883 using client id ANDROID_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXX
ecoflow_exporter  | 2026-04-09 12:03:49,992 INFO    Subscribed to MQTT topic /app/device/property/BKxxxxxxxxxxxxxx
ecoflow_exporter  | Exception in thread paho-mqtt-client-ANDROID_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXX:
ecoflow_exporter  | Traceback (most recent call last):
ecoflow_exporter  |   File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
ecoflow_exporter  |     self.run()
ecoflow_exporter  |   File "/usr/local/lib/python3.12/threading.py", line 1010, in run
ecoflow_exporter  |     self._target(*self._args, **self._kwargs)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4523, in _thread_main
ecoflow_exporter  |     self.loop_forever(retry_first_connection=True)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
ecoflow_exporter  |     rc = self._loop(timeout)
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
ecoflow_exporter  |     rc = self.loop_read()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
ecoflow_exporter  |     rc = self._packet_read()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
ecoflow_exporter  |     rc = self._packet_handle()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
ecoflow_exporter  |     return self._handle_publish()
ecoflow_exporter  |            ^^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
ecoflow_exporter  |     self._handle_on_message(message)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
ecoflow_exporter  |     on_message(self, self._userdata, message)
ecoflow_exporter  |   File "/ecoflow_exporter.py", line 187, in on_message
ecoflow_exporter  |     self.message_queue.put(message.payload.decode("utf-8"))
ecoflow_exporter  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 5: invalid continuation byte
ecoflow_exporter  | 2026-04-09 12:03:56,523 INFO    Received signal 15. Exiting...
ecoflow_exporter  | 2026-04-09 12:04:00,244 INFO    Login to EcoFlow API https://api.ecoflow.com/auth/login
ecoflow_exporter  | 2026-04-09 12:04:00,411 INFO    Successfully logged in: EcoFlow User
ecoflow_exporter  | 2026-04-09 12:04:00,411 INFO    Requesting IoT MQTT credentials https://api.ecoflow.com/iot-auth/app/certification
ecoflow_exporter  | 2026-04-09 12:04:00,542 INFO    Successfully extracted account: app-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
ecoflow_exporter  | 2026-04-09 12:04:00,599 INFO    Connecting to MQTT Broker mqtt-e.ecoflow.com:8883 using client id ANDROID_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXX
ecoflow_exporter  | 2026-04-09 12:04:00,756 INFO    Subscribed to MQTT topic /app/device/property/BKxxxxxxxxxxxxxx
ecoflow_exporter  | Exception in thread paho-mqtt-client-ANDROID_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXX:
ecoflow_exporter  | Traceback (most recent call last):
ecoflow_exporter  |   File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
ecoflow_exporter  |     self.run()
ecoflow_exporter  |   File "/usr/local/lib/python3.12/threading.py", line 1010, in run
ecoflow_exporter  |     self._target(*self._args, **self._kwargs)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4523, in _thread_main
ecoflow_exporter  |     self.loop_forever(retry_first_connection=True)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
ecoflow_exporter  |     rc = self._loop(timeout)
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 1686, in _loop
ecoflow_exporter  |     rc = self.loop_read()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 2100, in loop_read
ecoflow_exporter  |     rc = self._packet_read()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
ecoflow_exporter  |     rc = self._packet_handle()
ecoflow_exporter  |          ^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
ecoflow_exporter  |     return self._handle_publish()
ecoflow_exporter  |            ^^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
ecoflow_exporter  |     self._handle_on_message(message)
ecoflow_exporter  |   File "/usr/local/lib/python3.12/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
ecoflow_exporter  |     on_message(self, self._userdata, message)
ecoflow_exporter  |   File "/ecoflow_exporter.py", line 187, in on_message
ecoflow_exporter  |     self.message_queue.put(message.payload.decode("utf-8"))
ecoflow_exporter  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ecoflow_exporter  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 5: invalid continuation byte
ecoflow_exporter  | 2026-04-09 12:04:10,689 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:04:20,689 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:04:30,690 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:04:40,690 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:04:50,691 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:00,692 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:10,689 ERROR   No messages received for 60 seconds. Reconnecting to MQTT
ecoflow_exporter  | 2026-04-09 12:05:10,694 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:10,803 INFO    Connecting to MQTT Broker mqtt-e.ecoflow.com:8883 using client id ANDROID_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXX
ecoflow_exporter  | 2026-04-09 12:05:11,497 INFO    Reconnection successful, continuing
ecoflow_exporter  | 2026-04-09 12:05:20,695 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:30,696 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:40,697 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:05:50,697 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:00,698 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:10,699 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:20,699 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:30,700 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:40,700 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:06:50,701 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:00,702 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:10,702 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:20,703 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:30,703 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:40,704 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:07:50,705 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:00,705 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:10,706 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:20,707 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:30,707 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:40,708 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:08:50,708 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:00,709 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:10,710 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:20,710 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:30,710 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:40,711 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:09:50,712 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:00,715 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:10,716 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:20,716 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:30,717 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:40,717 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:10:50,718 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:11:00,718 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:11:10,719 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:11:20,720 INFO    Message queue is empty. Assuming that the device is offline
ecoflow_exporter  | 2026-04-09 12:11:30,720 INFO    Message queue is empty. Assuming that the device is offline
```
